openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /dashboard/:
    get:
      operationId: dashboard_retrieve
      tags:
      - dashboard
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /reports/report-writer/:
    post:
      operationId: reports_report_writer_create
      tags:
      - reports
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
