# Generated by Django 5.2.2 on 2025-06-10 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_time_of_day_rename_time_of_data_environment_type'),
        ('data', '0002_remove_noisedataset_environment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Environment_Type',
        ),
        migrations.DeleteModel(
            name='Specific_Mix_Setting',
        ),
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category'),
        ),
        migrations.AddField(
            model_name='subclass',
            name='parent_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.class'),
        ),
    ]
