# Generated by Django 5.2.2 on 2025-06-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='core.region'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microphone_type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time_of_day',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
