# Generated by Django 5.2.2 on 2026-02-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_category_name_alter_class_name_and_more"),
        ("data", "0018_dataset_rename_created_by_bulkreprocessingtask_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="data_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="data.dataset",
            ),
        ),
        migrations.CreateModel(
            name="CleanSpeechCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "data_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CleanSpeechClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="core.cleanspeechcategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "category")},
            },
        ),
        migrations.CreateModel(
            name="CleanSpeechSubClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subclasses",
                        to="core.cleanspeechclass",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "parent_class")},
            },
        ),
    ]
