# Generated by Django 5.2.2 on 2025-09-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_category_name_alter_class_name_and_more"),
        ("data", "0022_alter_noisedataset_dataset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="data_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="data.dataset",
            ),
        ),
    ]
