# Generated by Django 5.2.2 on 2026-02-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_category_data_type_cleanspeechcategory_and_more"),
        ("core", "0009_create_cleanspeech_models"),
    ]

    operations = []
