# Generated by Django 5.2.2 on 2026-05-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_merge_20260211_1242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleanspeechclass",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="core.cleanspeechcategory",
            ),
        ),
        migrations.AlterField(
            model_name="cleanspeechsubclass",
            name="parent_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subclasses",
                to="core.cleanspeechclass",
            ),
        ),
    ]
