# Generated by Django 5.2.2 on 2025-06-08 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_time_of_day_rename_time_of_data_environment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Data set, auto generated', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Any additional notes about this recording', null=True)),
                ('audio', models.FileField(help_text='Upload audio file', upload_to='files/')),
                ('duration', models.CharField(help_text='Duration of the audio in seconds', max_length=100, null=True)),
                ('recording_date', models.DateTimeField(help_text='Date when recording was made', null=True)),
                ('recording_device', models.CharField(help_text='Recording Device (e.g., iPhone 16, Zoom H4n, etc.)', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('noise_id', models.CharField(blank=True, help_text='the noise_id,auto generated', max_length=20, null=True, unique=True)),
                ('category', models.ForeignKey(help_text='Category of the data ', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
                ('class_name', models.ForeignKey(help_text='Class of the data', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.class')),
                ('collector', models.ForeignKey(help_text='The person collecting this data', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(help_text='Specific community (Kotei, Adum, Ayeduase, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.community')),
                ('environment_type', models.ForeignKey(help_text='Environment Type (Urban, Rural, Coastal, Forested, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.environment_type')),
                ('microphone_type', models.ForeignKey(help_text='Microphone Type (Omnidirectional, Directional, etc.) - Skip if using mobile phone', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.microphone_type')),
                ('region', models.ForeignKey(help_text='Select the region where recording was made (Ashanti, Central, Greater Accra, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.region')),
                ('specific_mix_setting', models.ForeignKey(help_text='Specific Mix Setting (Roadside, Market, Residential area, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.specific_mix_setting')),
                ('time_of_day', models.ForeignKey(help_text='Time of Day (Day, Night, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.time_of_day')),
            ],
        ),
    ]
