# Generated by Django 5.2.2 on 2025-06-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noisedataset',
            name='environment_type',
        ),
        migrations.RemoveField(
            model_name='noisedataset',
            name='specific_mix_setting',
        ),
    ]
