# Generated by Django 5.2.2 on 2025-06-10 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subclass_delete_environment_type_and_more'),
        ('data', '0002_remove_noisedataset_environment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noisedataset',
            name='subclas',
            field=models.ForeignKey(help_text='Sub Class of the data', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subclass'),
        ),
        migrations.AlterField(
            model_name='noisedataset',
            name='community',
            field=models.ForeignKey(help_text='Environment Type (Urban, Rural, Coastal, Forested, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.community'),
        ),
    ]
