# Generated by Django 5.2.2 on 2025-06-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_description_alter_category_name_and_more'),
        ('data', '0003_noisedataset_sub_class_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noisedataset',
            name='subclas',
        ),
        migrations.AddField(
            model_name='noisedataset',
            name='subclass',
            field=models.ForeignKey(blank=True, help_text='Sub Class of the data', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subclass'),
        ),
    ]
