# Generated by Django 5.2.2 on 2025-06-11 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_noisedataset_subclas_noisedataset_subclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='noisedataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 11, 10, 46, 0, 178892, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
