# Generated by Django 5.2.2 on 2025-06-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_noisedataset_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noisedataset',
            name='duration',
            field=models.CharField(help_text='Duration of the audio in seconds', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='noisedataset',
            name='name',
            field=models.CharField(help_text='Name of Data set, auto generated', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='noisedataset',
            name='noise_id',
            field=models.CharField(blank=True, help_text='the noise_id,auto generated', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='noisedataset',
            name='recording_device',
            field=models.CharField(help_text='Recording Device (e.g., iPhone 16, Zoom H4n, etc.)', max_length=255),
        ),
    ]
