# Generated by Django 5.2.2 on 2025-06-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_visualizationpreset_audiofeature_noiseanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofeature',
            name='duration',
            field=models.FloatField(help_text='Duration of the audio in seconds', null=True),
        ),
    ]
