# Generated by Django 5.2.2 on 2025-06-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_audiofeature_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofeature',
            name='num_samples',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='audiofeature',
            name='sample_rate',
            field=models.IntegerField(null=True),
        ),
    ]
