# Generated by Django 5.2.2 on 2025-07-22 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_category_name_alter_class_name_and_more"),
        ("data", "0011_bulkupload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bulkupload",
            name="failed_uploads",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="metadata_json",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="status",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="successful_uploads",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="total_files",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="user",
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="audio_files",
            field=models.FileField(
                blank=True,
                help_text="Upload multiple audio files",
                null=True,
                upload_to="bulk_uploads/",
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="category",
            field=models.ForeignKey(
                help_text="Category of the data",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.category",
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="class_name",
            field=models.ForeignKey(
                help_text="Class of the data",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.class",
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="collector",
            field=models.ForeignKey(
                help_text="The person collecting this data",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="community",
            field=models.ForeignKey(
                help_text="Specific community where recordings were made",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.community",
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Any additional notes about these recordings",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="microphone_type",
            field=models.ForeignKey(
                help_text="Microphone Type",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.microphone_type",
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="recording_date",
            field=models.DateTimeField(
                help_text="Date when recordings were made", null=True
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="recording_device",
            field=models.CharField(
                help_text="Recording Device (e.g., iPhone 16, Zoom H4n, etc.)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="region",
            field=models.ForeignKey(
                help_text="Select the region where recordings were made",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.region",
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="subclass",
            field=models.ForeignKey(
                blank=True,
                help_text="Sub Class of the data",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.subclass",
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="time_of_day",
            field=models.ForeignKey(
                help_text="Time of Day (Day, Night, etc.)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.time_of_day",
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
