# Generated by Django 5.2.2 on 2025-07-22 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0012_remove_bulkupload_failed_uploads_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bulkupload",
            name="audio_files",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="category",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="class_name",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="collector",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="community",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="description",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="microphone_type",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="recording_date",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="recording_device",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="region",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="subclass",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="time_of_day",
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="results",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="uploader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="zip_file",
            field=models.FileField(null=True, upload_to="bulk_uploads/"),
        ),
    ]
