# Generated by Django 5.2.2 on 2025-07-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0013_remove_bulkupload_audio_files_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BulkUpload",
        ),
    ]
