# Generated by Django 5.2.2 on 2025-07-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0015_bulkaudioupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkaudioupload",
            name="metadata",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="bulkaudioupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("completed_with_errors", "Completed With Errors"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
