# Generated by Django 5.2.2 on 2025-08-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_bulkreprocessingtask"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bulkreprocessingtask",
            old_name="created_by",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="bulkreprocessingtask",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="bulkreprocessingtask",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="bulkreprocessingtask",
            name="failed_dataset_ids",
        ),
        migrations.RemoveField(
            model_name="bulkreprocessingtask",
            name="started_at",
        ),
        migrations.RemoveField(
            model_name="bulkreprocessingtask",
            name="successful_datasets",
        ),
        migrations.AddField(
            model_name="bulkreprocessingtask",
            name="current_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bulkreprocessingtask",
            name="current_status_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bulkreprocessingtask",
            name="failed_dataset_details",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bulkreprocessingtask",
            name="progress_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bulkreprocessingtask",
            name="result_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="bulkreprocessingtask",
            name="failed_datasets",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bulkreprocessingtask",
            name="processed_datasets",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bulkreprocessingtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("completed_with_errors", "Completed With Errors"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="bulkreprocessingtask",
            name="total_datasets",
            field=models.IntegerField(default=0),
        ),
    ]
