# Generated by Django 5.2.2 on 2026-02-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0019_remove_noisedataset_recording_recording_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cleanspeechdataset",
            name="recording",
        ),
    ]
