# Generated by Django 5.2.2 on 2026-02-11 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0020_remove_cleanspeechdataset_recording"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleanspeechdataset",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                help_text="The raw recording that was processed into this dataset",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.recording",
            ),
        ),
    ]
