# Generated by Django 5.2.2 on 2026-02-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0021_cleanspeechdataset_recording"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recording",
            name="device_info",
        ),
    ]
