# Generated by Django 5.2.2 on 2026-02-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0022_alter_noisedataset_dataset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="noisedataset",
            name="has_been_approved",
            field=models.BooleanField(
                default=False, help_text="Whether the recording has been approved"
            ),
        ),
        migrations.AddField(
            model_name="noisedataset",
            name="was_recorded",
            field=models.BooleanField(
                default=False, help_text="Whether the recording was recorded"
            ),
        ),
    ]
