# Generated by Django 5.2.2 on 2026-02-11 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_create_recording_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recording",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Recording",
                "verbose_name_plural": "Recordings",
            },
        ),
        migrations.AddField(
            model_name="recording",
            name="recording_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the recording was made", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The person who approved this recording",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recordings_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="audio",
            field=models.FileField(
                blank=True,
                help_text="Raw audio recording file",
                null=True,
                upload_to="recordings/",
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="contributor",
            field=models.ForeignKey(
                blank=True,
                help_text="The person who made this recording",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recordings_contributed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="duration",
            field=models.FloatField(
                blank=True, help_text="Duration of recording in seconds", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
