# Generated by Django 5.2.2 on 2026-02-09 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_noiserecording"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noisedataset",
            name="has_been_approved",
        ),
        migrations.RemoveField(
            model_name="noisedataset",
            name="was_recorded",
        ),
        migrations.RemoveField(
            model_name="noiserecording",
            name="collector",
        ),
        migrations.AddField(
            model_name="noisedataset",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                help_text="The recording that was made",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.noiserecording",
            ),
        ),
        migrations.AddField(
            model_name="noiserecording",
            name="approved",
            field=models.BooleanField(
                default=False, help_text="Whether the recording has been approved"
            ),
        ),
        migrations.AddField(
            model_name="noiserecording",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="noiserecording",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The person who approved this recording",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="noise_recordings_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="noiserecording",
            name="contributor",
            field=models.ForeignKey(
                help_text="The person who made this recording",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="noise_recordings_contributed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="noiserecording",
            name="audio",
            field=models.FileField(
                help_text="Raw audio recording file", null=True, upload_to="recordings/"
            ),
        ),
        migrations.AlterField(
            model_name="noiserecording",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="noiserecording",
            name="recording_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the recording was made"
            ),
        ),
    ]
