# Generated by Django 5.2.2 on 2026-05-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0029_add_clean_speech_to_visualization_preset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleanspeechdataset",
            name="recording_date",
            field=models.DateTimeField(
                db_index=True, help_text="Date when recording was made", null=True
            ),
        ),
        migrations.AlterField(
            model_name="noisedataset",
            name="recording_date",
            field=models.DateTimeField(
                db_index=True, help_text="Date when recording was made", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="approved",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="recording",
            name="recording_type",
            field=models.CharField(
                choices=[
                    ("clean_speech", "Clean Speech Recording"),
                    ("english_language", "english_language"),
                    ("scripted_speech", "scripted_speech"),
                ],
                default="clean_speech",
                help_text="Type of recording",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Processing"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                help_text="Processing status of the recording",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="visualizationpreset",
            name="clean_speech_dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visualization_presets",
                to="data.cleanspeechdataset",
            ),
        ),
    ]
