# Generated by Django 5.2.2 on 2026-06-29 01:02
"""P6-5 — add a btree index on data_noiseanalysis.mean_db (hot analytics column).

The data_insights analytics tools sort ("-avg_decibel"), aggregate (Avg/Max/Min),
filter (mean_db IS NOT NULL) and ORDER BY mean_db for the percentile_cont box-plot
distribution. Without an index, decibel ranking / grouping / distribution queries
full-scan data_noiseanalysis. This migration adds that index (and only that — no
unrelated schema changes).

DBA NOTE — large existing tables: ``AlterField(db_index=True)`` emits a plain
``CREATE INDEX``, which takes an ACCESS EXCLUSIVE-style lock that BLOCKS writes
to data_noiseanalysis for the duration of the build. On a large production table
this can cause a noticeable write stall. To avoid it, a DBA should instead create
the index CONCURRENTLY (which does not block writes) and have Django record it as
already-applied:

    -- Run OUTSIDE a transaction (CONCURRENTLY cannot run in one):
    CREATE INDEX CONCURRENTLY data_noiseanalysis_mean_db_idx
        ON data_noiseanalysis (mean_db);

then fake this migration:  python manage.py migrate data 0031 --fake

Equivalently, for a managed rollout, replace the AlterField below with
django.contrib.postgres.operations.AddIndexConcurrently (and set
``atomic = False`` on the Migration), e.g.:

    from django.contrib.postgres.operations import AddIndexConcurrently
    from django.db.models import Index
    atomic = False
    operations = [AddIndexConcurrently("noiseanalysis",
        Index(fields=["mean_db"], name="data_noiseanalysis_mean_db_idx"))]

The default AlterField form below is kept because it is the additive change that
makemigrations produces from the model and is safe on small/empty tables.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0030_add_db_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noiseanalysis",
            name="mean_db",
            field=models.FloatField(
                db_index=True, help_text="Mean decibel level", null=True
            ),
        ),
    ]
