# Generated by Django 5.2.2 on 2026-05-12 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_message_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseURL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=2048, unique=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Human-readable label for this URL", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What kind of questions this URL helps answer (e.g. 'RAIL lab info, admissions, research')",
                    ),
                ),
                (
                    "refresh_frequency",
                    models.CharField(
                        choices=[
                            ("manual", "Manual only"),
                            ("hourly", "Every hour"),
                            ("daily", "Every day"),
                            ("weekly", "Every week"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("max_chars_per_fetch", models.IntegerField(default=8000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("last_fetch_success", models.BooleanField(default=False)),
                ("last_fetch_error", models.TextField(blank=True)),
                ("total_chunks", models.IntegerField(default=0)),
                ("total_chars", models.IntegerField(default=0)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_urls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base URL",
                "verbose_name_plural": "Knowledge Base URLs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-last_fetched_at"],
                        name="chatbot_kno_is_acti_2f0ecf_idx",
                    ),
                    models.Index(
                        fields=["refresh_frequency"],
                        name="chatbot_kno_refresh_51b6c3_idx",
                    ),
                ],
            },
        ),
    ]
