# Generated by Django 5.2.2 on 2025-12-06 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_name",
                    models.CharField(help_text="Name of the export", max_length=255),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, help_text="Celery task ID", max_length=255
                    ),
                ),
                (
                    "folder_structure",
                    models.JSONField(help_text="Folder structure configuration (JSON)"),
                ),
                (
                    "audio_structure_template",
                    models.TextField(blank=True, help_text="Audio subfolder template"),
                ),
                (
                    "download_url",
                    models.URLField(
                        blank=True, help_text="URL to download the ZIP file"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        help_text="Size of the ZIP file in bytes", null=True
                    ),
                ),
                (
                    "total_files",
                    models.IntegerField(
                        default=0, help_text="Total number of audio files exported"
                    ),
                ),
                (
                    "category_ids",
                    models.JSONField(
                        blank=True, help_text="Selected category IDs", null=True
                    ),
                ),
                (
                    "applied_filters",
                    models.JSONField(
                        blank=True, help_text="Applied filters (JSON)", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if export failed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the export",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="export_expo_user_id_981499_idx",
                    ),
                    models.Index(
                        fields=["status"], name="export_expo_status_c43f7f_idx"
                    ),
                    models.Index(
                        fields=["task_id"], name="export_expo_task_id_c32a55_idx"
                    ),
                ],
            },
        ),
    ]
