# Generated by Django 5.2.2 on 2025-12-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exporthistory",
            name="download_url",
            field=models.TextField(
                blank=True, help_text="URL to download the ZIP file"
            ),
        ),
    ]
