# Generated by Django 5.2.2 on 2026-01-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0002_alter_exporthistory_download_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="exporthistory",
            name="download_urls",
            field=models.JSONField(
                blank=True,
                help_text="List of download URLs for split exports",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exporthistory",
            name="file_sizes",
            field=models.JSONField(
                blank=True, help_text="List of file sizes for split exports", null=True
            ),
        ),
        migrations.AddField(
            model_name="exporthistory",
            name="split_count",
            field=models.IntegerField(
                default=1,
                help_text="Number of files to split the export into (1, 2, or 3)",
            ),
        ),
        migrations.AlterField(
            model_name="exporthistory",
            name="download_url",
            field=models.TextField(
                blank=True,
                help_text="URL to download the ZIP file (or first file if split)",
            ),
        ),
        migrations.AlterField(
            model_name="exporthistory",
            name="file_size",
            field=models.BigIntegerField(
                help_text="Size of the ZIP file in bytes (or first file if split)",
                null=True,
            ),
        ),
    ]
