"""
Django settings for datacollection project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv

import os
import logging


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

logger = logging.getLogger(__name__)


def as_bool(value):
    if not value:
        return False
    return str(value).lower() in ["true", "yes"]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = as_bool(os.getenv("DEBUG", "False"))

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY must come from the environment (.env, which is gitignored). Fail
# fast in non-DEBUG environments so the app never boots with SECRET_KEY=None.
# In DEBUG we fall back to a clearly-labeled insecure dev key so local
# development works without a .env. Never log or print the secret.
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-DEV-ONLY-do-not-use-in-production"
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is not set. Set it in your .env "
            "(gitignored) or environment before running with DEBUG=False."
        )

ALLOWED_HOSTS = [
    "localhost",
    "206.189.238.225",
    "127.0.0.1",
    "www.ihearandsee-at-rail.com",
    "ihearandsee-at-rail.com",
    "nyc1-88878471021e.zeddy-dev.onstagingocean.app",
    "api.ipify.org",
]


# Application definition

INSTALLED_APPS = [
    # optional, if special form elements are needed
    "storages",
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "django.contrib.admin",
    "tailwind",
    "theme",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "data",
    "core",
    "authentication",
    "data_insights",
    "approval",
    "export",
    "datacollection",
    "django_celery_results",
    "reports",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "onboarding",
    "chatbot",
]
TAILWIND_APP_NAME = "theme"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "datacollection.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "datacollection.wsgi.application"


# Database
USE_SQLITE = as_bool(os.getenv("USE_SQLITE", "False"))

if USE_SQLITE:
    print("Using local database")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "datacollection",
            "USER": "kelvin",
            "PASSWORD": "kelvin",
            "HOST": "localhost",
            "PORT": 5432,
        }
    }
else:
    print("Using PostgreSQL database")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "iheardatadb"),
            "USER": os.getenv("POSTGRES_USER", "postgres"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "localhost"),
            "HOST": os.getenv("POSTGRES_HOST", "db"),
            "PORT": int(os.getenv("POSTGRES_PORT", 5432)),
            "OPTIONS": {"sslmode": os.getenv("PGSSLMODE", "prefer")},
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    # Throttle rates. The "ai_insight" scope backs AIInsightRateThrottle on the
    # AI chat/message endpoints (data_insights). The rate is sourced from
    # AI_INSIGHT["SECURITY"]["RATE_LIMIT_PER_MINUTE"] (env:
    # AI_INSIGHT_RATE_LIMIT_PER_MINUTE), default 30/min per user — generous
    # enough not to break existing clients while bounding LLM spend.
    "DEFAULT_THROTTLE_RATES": {
        "ai_insight": f"{os.getenv('AI_INSIGHT_RATE_LIMIT_PER_MINUTE', 30)}/min",
    },
}


SPECTACTULAR_SETTINGS = {
    "TITLE": "Data Collection API",
    "DESCRIPTION": "API for Data Collection",
    "VERSION": "1.0.0",
}


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "authentication.CustomUser"


# Email Configuration
if as_bool(os.getenv("USE_SMTP_EMAIL", "True")):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")


# Authentication settings
LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/auth/login/"


UNFOLD = {
    "SITE_TITLE": "I hear Dataset Admin Portal",
    "SITE_HEADER": "I hear Dataset",
    "DARK_MODE": True,
    "LOGIN": {
        "image": "/static/assets/img/image.png",
        "title": "Welcome to I hear Dataset Admin Portal",
        "description": "Please enter your credentials",
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
    },
}

# NOTE: CORS settings were removed because django-cors-headers is NOT installed
# and CorsMiddleware is NOT in MIDDLEWARE, so CORS_ALLOWED_ORIGINS /
# CORS_ALLOW_CREDENTIALS were a no-op (dead config). To properly enable CORS for
# a separate frontend in the future:
#   1) pip install django-cors-headers
#   2) add "corsheaders" to INSTALLED_APPS
#   3) add "corsheaders.middleware.CorsMiddleware" high in MIDDLEWARE
#      (before CommonMiddleware)
#   4) then re-add CORS_ALLOWED_ORIGINS / CORS_ALLOW_CREDENTIALS here.


CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://localhost",
    "http://0.0.0.0",
    "http://206.189.238.225",
    "https://ihearandsee-at-rail.com",
    "http://ihearandsee-at-rail.com",
    "https://www.ihearandsee-at-rail.com",
]


USE_S3 = os.getenv("USE_S3", "False").lower() == "true"

if USE_S3:
    # DigitalOcean Spaces Settings
    AWS_ACCESS_KEY_ID = os.getenv("DO_SPACES_KEY")
    AWS_SECRET_ACCESS_KEY = os.getenv("DO_SPACES_SECRET")
    AWS_STORAGE_BUCKET_NAME = os.getenv("DO_SPACES_BUCKET")
    AWS_S3_ENDPOINT_URL = os.getenv(
        "DO_SPACES_ENDPOINT", "https://lon1.digitaloceanspaces.com"
    )

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "endpoint_url": AWS_S3_ENDPOINT_URL,
                "location": "media",
                "default_acl": "public-read",
                "object_parameters": {"CacheControl": "max-age=86400"},
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "endpoint_url": AWS_S3_ENDPOINT_URL,
                "location": "static",
                "default_acl": "public-read",
                "object_parameters": {"CacheControl": "max-age=86400"},
            },
        },
    }

if USE_S3:
    STATIC_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/static/"
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/"
else:
    # Local file storage
    STATIC_URL = "/static/"
    MEDIA_URL = "/media/"
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


# Read HTTPS config from proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Transport / cookie hardening. All gated on `not DEBUG` so local development
# (typically plain HTTP) is unaffected. In production (DEBUG=False) cookies are
# marked Secure, HTTP is redirected to HTTPS, and HSTS is advertised.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Redis
REDIS_USERNAME = os.getenv("REDIS_USERNAME", default="default")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", default="default")
REDIS_USE_TLS = as_bool(os.getenv("REDIS_USE_TLS", default="False"))
REDIS_HOST = os.getenv("REDIS_HOST", default="localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", default="6379"))
if REDIS_USE_TLS:
    REDIS_URL = f"rediss://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
else:
    REDIS_URL = f"redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
CACHE_TIMEOUT = int(os.getenv("CACHE_TIMEOUT", default=3600))
CACHE_DB_ID = int(os.getenv("CACHE_DB_ID", default="1"))

# Channels (WebSocket)
CHANNEL_LAYER_DB_ID = int(os.getenv("CHANNEL_LAYER_DB_ID", default="0"))
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"{REDIS_URL}/{CHANNEL_LAYER_DB_ID}"],
        },
    },
}
THROTTLE_RATE = os.getenv("THROTTLE_RATE", "100/s")


# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True

# Bulk task timeouts
CELERY_TASK_TIME_LIMIT = 6 * 60 * 60  # 6 hours
CELERY_TASK_SOFT_TIME_LIMIT = 5 * 60 * 60  # 5 hours

CELERY_BROKER_DB_ID = int(os.getenv("CELERY_BROKER_DB_ID", default="2"))
CELERY_RESULT_BACKEND_DB_ID = int(os.getenv("CELERY_RESULT_BACKEND_DB_ID", default="3"))
CELERY_BROKER_URL = f"{REDIS_URL}/{CELERY_BROKER_DB_ID}"

# Store results in the database by default to prevent Redis from filling up
USE_DB_RESULT_BACKEND = as_bool(os.getenv("USE_DB_RESULT_BACKEND", default="True"))
if USE_DB_RESULT_BACKEND:
    CELERY_RESULT_BACKEND = "django-db"
    CELERY_RESULT_EXTENDED = True
else:
    CELERY_RESULT_BACKEND = f"{REDIS_URL}/{CELERY_RESULT_BACKEND_DB_ID}"
    if REDIS_USE_TLS:
        CELERY_RESULT_BACKEND += "?ssl_cert_reqs=required"
    CELERY_RESULT_EXPIRES = 300
    CELERY_RESULT_BACKEND_ALWAYS_RETRY = True
    CELERY_RESULT_BACKEND_MAX_RETRIES = 10

if REDIS_USE_TLS:
    CELERY_BROKER_URL += "?ssl_cert_reqs=required"

CELERY_TASK_ALWAYS_EAGER = as_bool(
    os.getenv("CELERY_TASK_ALWAYS_EAGER", default="False")
)

# Safety + stability settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = 200
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 500000

CELERY_BEAT_SCHEDULE = {
    "cleanup-old-sessions": {
        "task": "chatbot.tasks.cleanup_old_sessions_task",
        "schedule": 3600.0,
    },
    "clear-expired-cache": {
        "task": "chatbot.tasks.clear_cache_task",
        "schedule": 1800.0,
    },
}


# Directory for assembling large/chunked uploads before background processing
SHARED_UPLOADS_DIR = os.getenv("SHARED_UPLOADS_DIR", "/shared_uploads")

# CHATBOT configuration - RAG uses FAISS only (fast, no Chroma)
CHATBOT = {
    "FAISS_VECTOR_STORE": {
        "PATH": "vector_store",  # relative to BASE_DIR; shared volume in Docker
    },
    "EMBEDDINGS": {
        "MODEL": "text-embedding-3-small",
        "DIMENSIONS": 1536,
    },
    "RAG": {
        "CHUNK_SIZE": 1000,
        "CHUNK_OVERLAP": 200,
        "TOP_K_RESULTS": 4,
        "ENABLE_RERANKING": True,
        "STREAMING_ENABLED": True,
    },
    "RATE_LIMITS": {
        "MESSAGES_PER_MINUTE": 30,
        "DOCUMENTS_PER_DAY": 50,
    },
    "DOCUMENT": {
        "MAX_FILE_SIZE_MB": 25,
        "ALLOWED_EXTENSIONS": ["pdf", "docx", "txt", "md"],
        "ENABLE_OCR": True,
    },
}

# Single canonical path for FAISS vector store: used by document processing (Celery)
# and retrieval (web). Override with FAISS_VECTOR_STORE_PATH for absolute path (e.g. Docker).
FAISS_VECTOR_STORE_PATH = os.getenv(
    "FAISS_VECTOR_STORE_PATH",
    os.path.join(BASE_DIR, CHATBOT["FAISS_VECTOR_STORE"]["PATH"]),
)

OPENAI_MODEL = os.getenv("OPENAI_MODEL", default="gpt-4o-mini")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

if USE_SQLITE:
    # Local development: use local Postgres (localhost)
    AI_INSIGHT = {
        "DATABASE": {
            "USER": os.getenv("LOCAL_POSTGRES_USER", "kelvin"),
            "PASSWORD": os.getenv("LOCAL_POSTGRES_PASSWORD", "kelvin"),
            "HOST": os.getenv("LOCAL_POSTGRES_HOST", "localhost"),
            "PORT": int(os.getenv("LOCAL_POSTGRES_PORT", 5432)),
            "NAME": os.getenv("LOCAL_POSTGRES_DB", "datacollection"),
            # Optional dedicated least-privilege read-only credentials for the
            # NL->SQL agent engine. If unset, the agent falls back to the creds
            # above with a loud logger.warning (see sql_agent.py). See the SQL in
            # sql_agent.py for creating a least-privilege read-only role.
            "READONLY_USER": os.getenv("AI_INSIGHT_DB_READONLY_USER", ""),
            "READONLY_PASSWORD": os.getenv("AI_INSIGHT_DB_READONLY_PASSWORD", ""),
            "MAX_CONNECTIONS": int(os.getenv("AI_INSIGHT_DB_MAX_CONNECTIONS", 20)),
            "CONNECTION_TIMEOUT": int(
                os.getenv("AI_INSIGHT_DB_CONNECTION_TIMEOUT", 30)
            ),
            # Postgres statement_timeout (seconds) applied to every NL->SQL agent
            # connection. Kills runaway/cartesian queries even if the regex guard
            # is bypassed. Generous enough for legitimate aggregations.
            "STATEMENT_TIMEOUT_SECONDS": int(
                os.getenv("AI_INSIGHT_SQL_TIMEOUT_SECONDS", 15)
            ),
        },
        "AGENT": {
            "MODEL": OPENAI_MODEL,
            "MAX_RETRIES": int(os.getenv("AI_INSIGHT_MAX_RETRIES", 3)),
            "TIMEOUT_SECONDS": int(os.getenv("AI_INSIGHT_TIMEOUT_SECONDS", 120)),
            "DEFAULT_TOP_K": int(os.getenv("AI_INSIGHT_DEFAULT_TOP_K", 100)),
            "MAX_TOP_K": int(os.getenv("AI_INSIGHT_MAX_TOP_K", 1000)),
            # Caps LLM output tokens per call to bound worst-case spend.
            "MAX_TOKENS": int(os.getenv("AI_INSIGHT_MAX_TOKENS", 2000)),
            # Bounds LangGraph tool-loop depth per run to bound worst-case spend.
            "RECURSION_LIMIT": int(os.getenv("AI_INSIGHT_RECURSION_LIMIT", 15)),
            "ENABLE_CACHING": as_bool(os.getenv("AI_INSIGHT_ENABLE_CACHING", "True")),
            "CLARIFICATION_V2_ENABLED": as_bool(
                os.getenv("AI_INSIGHT_CLARIFICATION_V2_ENABLED", "False")
            ),
        },
        "SECURITY": {
            "DEFAULT_ALLOWED_TABLES": [],
            "MAX_SESSIONS_PER_USER": int(
                os.getenv("AI_INSIGHT_MAX_SESSIONS_PER_USER", 10)
            ),
            "SESSION_INACTIVITY_HOURS": int(
                os.getenv("AI_INSIGHT_SESSION_INACTIVITY_HOURS", 24)
            ),
            "RATE_LIMIT_PER_MINUTE": int(
                os.getenv("AI_INSIGHT_RATE_LIMIT_PER_MINUTE", 30)
            ),
            "MAX_MESSAGE_LENGTH": int(
                os.getenv("AI_INSIGHT_MAX_MESSAGE_LENGTH", 10000)
            ),
        },
    }
else:
    # Docker / production: use Postgres from env (host "db" in Docker)
    AI_INSIGHT = {
        "DATABASE": {
            "USER": os.getenv("POSTGRES_USER", "postgres"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "localhost"),
            "HOST": os.getenv("POSTGRES_HOST", "db"),
            "PORT": int(os.getenv("POSTGRES_PORT", 5432)),
            "NAME": os.getenv("POSTGRES_DB", "iheardatadb"),
            # Optional dedicated least-privilege read-only credentials for the
            # NL->SQL agent engine. If unset, the agent falls back to the creds
            # above with a loud logger.warning (see sql_agent.py). See the SQL in
            # sql_agent.py for creating a least-privilege read-only role.
            "READONLY_USER": os.getenv("AI_INSIGHT_DB_READONLY_USER", ""),
            "READONLY_PASSWORD": os.getenv("AI_INSIGHT_DB_READONLY_PASSWORD", ""),
            "MAX_CONNECTIONS": int(os.getenv("AI_INSIGHT_DB_MAX_CONNECTIONS", 20)),
            "CONNECTION_TIMEOUT": int(
                os.getenv("AI_INSIGHT_DB_CONNECTION_TIMEOUT", 30)
            ),
            # Postgres statement_timeout (seconds) applied to every NL->SQL agent
            # connection. Kills runaway/cartesian queries even if the regex guard
            # is bypassed. Generous enough for legitimate aggregations.
            "STATEMENT_TIMEOUT_SECONDS": int(
                os.getenv("AI_INSIGHT_SQL_TIMEOUT_SECONDS", 15)
            ),
        },
        "AGENT": {
            "MODEL": OPENAI_MODEL,
            "MAX_RETRIES": int(os.getenv("AI_INSIGHT_MAX_RETRIES", 3)),
            "TIMEOUT_SECONDS": int(os.getenv("AI_INSIGHT_TIMEOUT_SECONDS", 120)),
            "DEFAULT_TOP_K": int(os.getenv("AI_INSIGHT_DEFAULT_TOP_K", 100)),
            "MAX_TOP_K": int(os.getenv("AI_INSIGHT_MAX_TOP_K", 1000)),
            # Caps LLM output tokens per call to bound worst-case spend.
            "MAX_TOKENS": int(os.getenv("AI_INSIGHT_MAX_TOKENS", 2000)),
            # Bounds LangGraph tool-loop depth per run to bound worst-case spend.
            "RECURSION_LIMIT": int(os.getenv("AI_INSIGHT_RECURSION_LIMIT", 15)),
            "ENABLE_CACHING": as_bool(os.getenv("AI_INSIGHT_ENABLE_CACHING", "True")),
            "CLARIFICATION_V2_ENABLED": as_bool(
                os.getenv("AI_INSIGHT_CLARIFICATION_V2_ENABLED", "False")
            ),
        },
        "SECURITY": {
            "DEFAULT_ALLOWED_TABLES": [],
            "MAX_SESSIONS_PER_USER": int(
                os.getenv("AI_INSIGHT_MAX_SESSIONS_PER_USER", 10)
            ),
            "SESSION_INACTIVITY_HOURS": int(
                os.getenv("AI_INSIGHT_SESSION_INACTIVITY_HOURS", 24)
            ),
            "RATE_LIMIT_PER_MINUTE": int(
                os.getenv("AI_INSIGHT_RATE_LIMIT_PER_MINUTE", 30)
            ),
            "MAX_MESSAGE_LENGTH": int(
                os.getenv("AI_INSIGHT_MAX_MESSAGE_LENGTH", 10000)
            ),
        },
    }


# Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"{REDIS_URL}/{CACHE_DB_ID}",
    }
}
