"""
Django settings for datacollection project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv

# import sys
import os
import logging

# from django.templatetags.static import static


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

logger = logging.getLogger(__name__)


def as_bool(value: str):
    return value.lower() in ["true", "yes"]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*_^$!#mp28jhe25iq6dok5suz(_!529k-c2hj#wnd!7@6@p%ri"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = [
    "localhost",
    "206.189.238.225",
    "127.0.0.1",
    "www.ihearandsee-at-rail.com",
    "ihearandsee-at-rail.com",
    "nyc1-88878471021e.zeddy-dev.onstagingocean.app",
    "api.ipify.org",
]


# Application definition

INSTALLED_APPS = [
    # optional, if special form elements are needed
    "storages",
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "django.contrib.admin",
    "tailwind",
    "theme",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "data",
    "core",
    "authentication",
    "data_insights",
    "approval",
    "export",
    "datacollection",
    "django_celery_results",
    "reports",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "onboarding",
]
TAILWIND_APP_NAME = "theme"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "datacollection.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "datacollection.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# settings.py
USE_SQLITE = as_bool(os.getenv("USE_SQLITE", "False"))

if USE_SQLITE:
    print("Using local database")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "datacollection",
            "USER": "kelvin",
            "PASSWORD": "kelvin",
            "HOST": "localhost",
            "PORT": 5432,
        }
    }
else:
    print("Using PostgreSQL database")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "iheardatadb"),
            "USER": os.getenv("POSTGRES_USER", "postgres"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "localhost"),
            "HOST": os.getenv("POSTGRES_HOST", "db"),
            "PORT": int(os.getenv("POSTGRES_PORT", 5432)),
            "OPTIONS": {"sslmode": os.getenv("PGSSLMODE", "prefer")},
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,  # default page size
}


SPECTACTULAR_SETTINGS = {
    "TITLE": "Data Collection API",
    "DESCRIPTION": "API for Data Collection",
    "VERSION": "1.0.0",
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "authentication.CustomUser"


# Email Configuration
if bool(os.getenv("USE_SMTP_EMAIL", True)):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")


# Authentication settings
LOGIN_URL = "/auth/login/"  # URL to redirect to for login
LOGIN_REDIRECT_URL = "/"  # Where to redirect after login
LOGOUT_REDIRECT_URL = "/auth/login/"


# Alternative approach without lambda (simpler):
UNFOLD = {
    "SITE_TITLE": "I hear Dataset Admin Portal",
    "SITE_HEADER": "I hear Dataset",
    "DARK_MODE": True,
    "LOGIN": {
        "image": "/static/assets/img/image.png",
        "title": "Welcome to I hear Dataset Admin Portal",
        "description": "Please enter your credentials",
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
    },
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost",  # Your frontend URL
    "http://127.0.0.10",
    "http://0.0.0.0",
    "http://206.189.238.225",
    "www.ihearandsee-at-rail.com",
    "ihearandsee-at-rail.com",
    "https://ihearandsee-at-rail.com",
    "http://ihearandsee-at-rail.com",
    "https://www.ihearandsee-at-rail.com",
    "nyc1-88878471021e.zeddy-dev.onstagingocean.app",
]


CORS_ALLOW_CREDENTIALS = True  # To allow cookies


CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://localhost",
    "http://0.0.0.0",
    "http://206.189.238.225",
    "https://ihearandsee-at-rail.com",
    "http://ihearandsee-at-rail.com",
    "https://www.ihearandsee-at-rail.com",
]


USE_S3 = os.getenv("USE_S3", "False").lower() == "true"

if USE_S3:
    # DigitalOcean Spaces Settings
    AWS_ACCESS_KEY_ID = os.getenv("DO_SPACES_KEY")
    AWS_SECRET_ACCESS_KEY = os.getenv("DO_SPACES_SECRET")
    AWS_STORAGE_BUCKET_NAME = os.getenv("DO_SPACES_BUCKET")
    AWS_S3_ENDPOINT_URL = os.getenv(
        "DO_SPACES_ENDPOINT", "https://lon1.digitaloceanspaces.com"
    )

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "endpoint_url": AWS_S3_ENDPOINT_URL,
                "location": "media",
                "default_acl": "public-read",
                "object_parameters": {"CacheControl": "max-age=86400"},
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "endpoint_url": AWS_S3_ENDPOINT_URL,
                "location": "static",
                "default_acl": "public-read",
                "object_parameters": {"CacheControl": "max-age=86400"},
            },
        },
    }

    STATIC_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/static/"
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/"
else:
    # Local file storage
    STATIC_URL = "/static/"
    MEDIA_URL = "/media/"
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


# READ HTTPS CONFIG FROM PROXY
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
REDIS_USERNAME = os.getenv("REDIS_USERNAME", default="default")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", default="default")
REDIS_USE_TLS = as_bool(os.getenv("REDIS_USE_TLS", default="False"))
REDIS_HOST = os.getenv("REDIS_HOST", default="localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", default="6379"))
if REDIS_USE_TLS:
    REDIS_URL = f"rediss://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
else:
    REDIS_URL = f"redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
CACHE_TIMEOUT = int(os.getenv("CACHE_TIMEOUT", default=3600))
# DJANGO CACHE
CACHE_DB_ID = int(os.getenv("CACHE_DB_ID", default="1"))
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"{REDIS_URL}/{CACHE_DB_ID}",
        # "OPTIONS": {"CACHE_TIMEOUT": CACHE_TIMEOUT},
    }
}
# CHANNELS FOR WEBSOCKET
CHANNEL_LAYER_DB_ID = int(os.getenv("CHANNEL_LAYER_DB_ID", default="0"))
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"{REDIS_URL}/{CHANNEL_LAYER_DB_ID}"],
        },
    },
}
THROTTLE_RATE = os.getenv("THROTTLE_RATE", "100/s")

# CELERY
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True

# Bulk task timeouts
CELERY_TASK_TIME_LIMIT = 6 * 60 * 60  # 6 hours
CELERY_TASK_SOFT_TIME_LIMIT = 5 * 60 * 60  # 5 hours

# Redis broker/backend
CELERY_BROKER_DB_ID = int(os.getenv("CELERY_BROKER_DB_ID", default="2"))
CELERY_RESULT_BACKEND_DB_ID = int(os.getenv("CELERY_RESULT_BACKEND_DB_ID", default="3"))
CELERY_BROKER_URL = f"{REDIS_URL}/{CELERY_BROKER_DB_ID}"
# Use database backend for results instead of Redis to prevent Redis from filling up
# django_celery_results is installed, so we can use database backend
USE_DB_RESULT_BACKEND = as_bool(os.getenv("USE_DB_RESULT_BACKEND", default="True"))
if USE_DB_RESULT_BACKEND:
    # Store results in database instead of Redis
    CELERY_RESULT_BACKEND = "django-db"
    CELERY_RESULT_EXTENDED = True
else:
    # Fallback to Redis if needed
    CELERY_RESULT_BACKEND = f"{REDIS_URL}/{CELERY_RESULT_BACKEND_DB_ID}"
    if REDIS_USE_TLS:
        CELERY_RESULT_BACKEND += "?ssl_cert_reqs=required"
    # Result expiration to prevent Redis from filling up
    CELERY_RESULT_EXPIRES = 300  # Expire results after 5 minutes
    CELERY_RESULT_BACKEND_ALWAYS_RETRY = True
    CELERY_RESULT_BACKEND_MAX_RETRIES = 10

if REDIS_USE_TLS:
    CELERY_BROKER_URL += "?ssl_cert_reqs=required"

CELERY_TASK_ALWAYS_EAGER = as_bool(
    os.getenv("CELERY_TASK_ALWAYS_EAGER", default="False")
)

# Safety + stability settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # One task at a time
CELERY_TASK_ACKS_LATE = True  # Ack after completion
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Requeue if worker dies
CELERY_WORKER_MAX_TASKS_PER_CHILD = 200  # Restart after 200 tasks
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 500000  # Restart if >500MB


# Directory for assembling large/chunked uploads before background processing
# Can be overridden via env var SHARED_UPLOADS_DIR
SHARED_UPLOADS_DIR = os.getenv("SHARED_UPLOADS_DIR", "/shared_uploads")


# open ai

OPENAI_MODEL = os.getenv("OPENAI_MODEL", default="gpt-4o-mini")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

if USE_SQLITE:

    AI_INSIGHT = {
        "DATABASE": {
            "USER": os.getenv("LOCAL_POSTGRES_USER", "postgres"),
            "PASSWORD": os.getenv("LOCAL_POSTGRES_PASSWORD", "localhost"),
            "HOST": os.getenv("LOCAL_POSTGRES_HOST", "db"),
            "PORT": int(os.getenv("LOCAL_POSTGRES_PORT", 5432)),
            "NAME": os.getenv("LOCAL_POSTGRES_DB", "iheardatadb"),
            "MAX_CONNECTIONS": int(os.getenv("AI_INSIGHT_DB_MAX_CONNECTIONS", 20)),
            "CONNECTION_TIMEOUT": int(
                os.getenv("AI_INSIGHT_DB_CONNECTION_TIMEOUT", 30)
            ),
        },
        "AGENT": {
            "MODEL": OPENAI_MODEL,
            "MAX_RETRIES": int(os.getenv("AI_INSIGHT_MAX_RETRIES", 3)),
            "TIMEOUT_SECONDS": int(os.getenv("AI_INSIGHT_TIMEOUT_SECONDS", 120)),
            "DEFAULT_TOP_K": int(os.getenv("AI_INSIGHT_DEFAULT_TOP_K", 100)),
            "MAX_TOP_K": int(os.getenv("AI_INSIGHT_MAX_TOP_K", 1000)),
            "ENABLE_CACHING": as_bool(os.getenv("AI_INSIGHT_ENABLE_CACHING", "True")),
        },
        "SECURITY": {
            "DEFAULT_ALLOWED_TABLES": [],
            "MAX_SESSIONS_PER_USER": int(
                os.getenv("AI_INSIGHT_MAX_SESSIONS_PER_USER", 10)
            ),
            "SESSION_INACTIVITY_HOURS": int(
                os.getenv("AI_INSIGHT_SESSION_INACTIVITY_HOURS", 24)
            ),
            "RATE_LIMIT_PER_MINUTE": int(
                os.getenv("AI_INSIGHT_RATE_LIMIT_PER_MINUTE", 30)
            ),
            "MAX_MESSAGE_LENGTH": int(
                os.getenv("AI_INSIGHT_MAX_MESSAGE_LENGTH", 10000)
            ),
        },
    }


else:

    AI_INSIGHT = {
        "DATABASE": {
            "USER": os.getenv("POSTGRES_USER", "postgres"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "localhost"),
            "HOST": os.getenv("POSTGRES_HOST", "db"),
            "PORT": int(os.getenv("POSTGRES_PORT", 5432)),
            "NAME": os.getenv("POSTGRES_DB", "iheardatadb"),
            "MAX_CONNECTIONS": int(os.getenv("AI_INSIGHT_DB_MAX_CONNECTIONS", 20)),
            "CONNECTION_TIMEOUT": int(
                os.getenv("AI_INSIGHT_DB_CONNECTION_TIMEOUT", 30)
            ),
        },
        "AGENT": {
            "MODEL": OPENAI_MODEL,
            "MAX_RETRIES": int(os.getenv("AI_INSIGHT_MAX_RETRIES", 3)),
            "TIMEOUT_SECONDS": int(os.getenv("AI_INSIGHT_TIMEOUT_SECONDS", 120)),
            "DEFAULT_TOP_K": int(os.getenv("AI_INSIGHT_DEFAULT_TOP_K", 100)),
            "MAX_TOP_K": int(os.getenv("AI_INSIGHT_MAX_TOP_K", 1000)),
            "ENABLE_CACHING": as_bool(os.getenv("AI_INSIGHT_ENABLE_CACHING", "True")),
        },
        "SECURITY": {
            "DEFAULT_ALLOWED_TABLES": [],
            "MAX_SESSIONS_PER_USER": int(
                os.getenv("AI_INSIGHT_MAX_SESSIONS_PER_USER", 10)
            ),
            "SESSION_INACTIVITY_HOURS": int(
                os.getenv("AI_INSIGHT_SESSION_INACTIVITY_HOURS", 24)
            ),
            "RATE_LIMIT_PER_MINUTE": int(
                os.getenv("AI_INSIGHT_RATE_LIMIT_PER_MINUTE", 30)
            ),
            "MAX_MESSAGE_LENGTH": int(
                os.getenv("AI_INSIGHT_MAX_MESSAGE_LENGTH", 10000)
            ),
        },
    }
