# Generated by Django 5.2.2 on 2025-06-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_user_id_customuser_speaker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, help_text='Optional. If not provided, a random password will be generated.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Optional. If not provided, one will be generated.', max_length=150, null=True, unique=True),
        ),
    ]
