# Generated by Django 5.2.2 on 2025-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_password_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unhashed_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
