# Generated by Django 5.2.2 on 2025-12-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_userotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contributor", "User"),
                    ("researcher", "Researcher"),
                    ("super_admin", "Super Admin"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
