# Generated by Django 5.2.2 on 2026-01-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_customuser_is_verified_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contributor", "Contributor"),
                    ("researcher", "Researcher"),
                    ("super_admin", "Super Admin"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
