# Generated by Django 5.2.2 on 2026-05-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_customuser_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="unhashed_password",
        ),
    ]
