# Generated by Django 5.2.2 on 2025-09-11 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_insights", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryCacheModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_id", models.CharField(max_length=100, unique=True)),
                ("query_type", models.CharField(max_length=50)),
                ("query_sql", models.TextField()),
                ("result_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("metadata", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_caches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["query_id"], name="data_insigh_query_i_c32982_idx"
                    ),
                    models.Index(
                        fields=["created_by", "created_at"],
                        name="data_insigh_created_e0ae5b_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="data_insigh_expires_670fc7_idx"
                    ),
                ],
            },
        ),
    ]
