# Generated by Django 5.2.2 on 2025-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_insights", "0002_querycachemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
