# Generated by Django 5.2.2 on 2026-05-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_insights", "0005_rename_visulization_chatmessage_visualization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("clarification_pending", "Clarification Pending"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
