# Generated by Django 5.1.7 on 2025-04-24 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_insight", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="allowed_tables",
        ),
    ]
