# Generated by Django 5.1.7 on 2025-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_insight", "0002_remove_chatsession_allowed_tables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="content",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="role",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="assistant_response",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="user_input",
            field=models.JSONField(default=dict),
        ),
    ]
