# Generated by Django 5.1.7 on 2025-04-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ai_insight",
            "0003_remove_chatmessage_content_remove_chatmessage_role_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="tool_call",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="assistant_response",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="user_input",
            field=models.TextField(),
        ),
    ]
