# Generated by Django 5.1.7 on 2025-07-11 07:28

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_insight", "0004_chatmessage_tool_call_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "permissions": [
                    ("use_ai_insight", "Can use AI Insight agent"),
                    ("manage_ai_sessions", "Can manage AI insight sessions"),
                ]
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="ai_answer_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("user", "User Message"),
                    ("assistant", "Assistant Response"),
                    ("system", "System Message"),
                    ("error", "Error Message"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="model_used",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="processing_time_ms",
            field=models.PositiveIntegerField(
                blank=True, help_text="Processing time in milliseconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="query_results",
            field=models.JSONField(
                blank=True, help_text="Raw query results", null=True
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sql_query",
            field=models.TextField(
                blank=True, default="", help_text="Generated SQL query"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="started_processing_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="token_count_input",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="token_count_output",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="total_messages",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="assistant_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="user_input",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(10000)]
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="ai_insight__session_2ab6e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "status"], name="ai_insight__session_1164df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["status"], name="ai_insight__status_a0be7f_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["created_at"], name="ai_insight__created_8f2915_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "status"], name="ai_insight__user_id_eb2198_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["created_at"], name="ai_insight__created_13cc98_idx"
            ),
        ),
    ]
