# Generated by Django 5.1.7 on 2025-07-11 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ai_insight",
            "0005_alter_chatsession_options_chatmessage_ai_answer_flag_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="ai_answer_flag",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="model_used",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="retry_count",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="started_processing_at",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="token_count_input",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="token_count_output",
        ),
    ]
