# Generated by Django 5.1.7 on 2025-07-11 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_insight", "0007_remove_chatmessage_query_results_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="message_type",
        ),
    ]
